# Generated by Django 4.2.2 on 2023-07-08 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0003_remove_shelter_contact'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='employer',
        ),
        migrations.AddField(
            model_name='profile',
            name='shelter',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shelters.shelter'),
        ),
    ]
