# Generated by Django 4.2.2 on 2023-07-04 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0002_shelter_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='contact',
        ),
    ]
