# Generated by Django 4.2.2 on 2023-07-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0005_alter_shelter_addressline1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='webSite',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
